/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ReturnsRefundsRouteImport } from './routes/returns-refunds'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as VerificationComplianceRouteImport } from './routes/verification-compliance'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCustomerServiceRouteImport } from './routes/admin.customer-service'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminMessengerRouteImport } from './routes/admin.messenger'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSystemLogsRouteImport } from './routes/admin.system-logs'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiScrapeRouteImport } from './routes/api/scrape'
import { Route as ApiSendNotificationRouteImport } from './routes/api/send-notification'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as CartLoginRouteImport } from './routes/cart.login'
import { Route as CartRegisterRouteImport } from './routes/cart.register'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ResellerSplatRouteImport } from './routes/reseller.$'
import { Route as ResellerAdBoostRouteImport } from './routes/reseller.ad-boost'
import { Route as ResellerDashboardRouteImport } from './routes/reseller.dashboard'
import { Route as ResellerLoginRouteImport } from './routes/reseller.login'
import { Route as ResellerMessagesRouteImport } from './routes/reseller.messages'
import { Route as ResellerOrdersRouteImport } from './routes/reseller.orders'
import { Route as ResellerProfileRouteImport } from './routes/reseller.profile'
import { Route as ResellerRegisterRouteImport } from './routes/reseller.register'
import { Route as ResellerShareTargetRouteImport } from './routes/reseller.share-target'
import { Route as ResellerShopRouteImport } from './routes/reseller.shop'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as AdminAchCustomersRouteImport } from './routes/admin.ach.customers'
import { Route as AdminAchFinancialRouteImport } from './routes/admin.ach.financial'
import { Route as AdminArsDepositRouteImport } from './routes/admin.ars.deposit'
import { Route as AdminArsOrdersRouteImport } from './routes/admin.ars.orders'
import { Route as AdminArsPaymentInfoRouteImport } from './routes/admin.ars.payment-info'
import { Route as AdminArsRetailShopsRouteImport } from './routes/admin.ars.retail-shops'
import { Route as AdminArsWithdrawalRouteImport } from './routes/admin.ars.withdrawal'
import { Route as AdminAuthForgotPasswordRouteImport } from './routes/admin.auth.forgot-password'
import { Route as AdminAuthSignInRouteImport } from './routes/admin.auth.sign-in'
import { Route as AdminCustomerCareOrderServicesRouteImport } from './routes/admin.customer-care.order-services'
import { Route as AdminCustomerCareResellerProfileRouteImport } from './routes/admin.customer-care.reseller-profile'
import { Route as AdminCustomerCareStaffsRouteImport } from './routes/admin.customer-care.staffs'
import { Route as AdminCustomerCareVirtualServicesRouteImport } from './routes/admin.customer-care.virtual-services'
import { Route as AdminSlaAdministratorRouteImport } from './routes/admin.sla.administrator'
import { Route as AdminSlaBroadcastNewsRouteImport } from './routes/admin.sla.broadcast-news'
import { Route as AdminSlaOwnershipRouteImport } from './routes/admin.sla.ownership'
import { Route as AdminSlaReseller2AdminRouteImport } from './routes/admin.sla.reseller-2-admin'
import { Route as AdminSlaSiteAdvertisingRouteImport } from './routes/admin.sla.site-advertising'
import { Route as AdminSlaSqcOrdersRouteImport } from './routes/admin.sla.sqc-orders'
import { Route as AdminSlaStaffRouteImport } from './routes/admin.sla.staff'
import { Route as ApipublicRegisterResellerRouteImport } from './routes/api/(public)/register-reseller'
import { Route as ApiAdminCreateAdminRouteImport } from './routes/api/admin/create-admin'
import { Route as ApiAdminCreateResellerRouteImport } from './routes/api/admin/create-reseller'
import { Route as ApiAdminDeleteResellerRouteImport } from './routes/api/admin/delete-reseller'
import { Route as ApiAdminDeleteStaffRouteImport } from './routes/api/admin/delete-staff'
import { Route as ApiAdminResetResellerPasswordRouteImport } from './routes/api/admin/reset-reseller-password'
import { Route as ApiAdminVerifyAllRouteImport } from './routes/api/admin/verify-all'
import { Route as ResellerProfileCustomizeRouteImport } from './routes/reseller.profile.customize'
import { Route as ApipublicResellerRequestResetRouteImport } from './routes/api/(public)/reseller/request-reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRefundsRoute = ReturnsRefundsRouteImport.update({
  id: '/returns-refunds',
  path: '/returns-refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationComplianceRoute = VerificationComplianceRouteImport.update({
  id: '/verification-compliance',
  path: '/verification-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerServiceRoute = AdminCustomerServiceRouteImport.update({
  id: '/admin/customer-service',
  path: '/admin/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessengerRoute = AdminMessengerRouteImport.update({
  id: '/admin/messenger',
  path: '/admin/messenger',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/admin/resellers',
  path: '/admin/resellers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemLogsRoute = AdminSystemLogsRouteImport.update({
  id: '/admin/system-logs',
  path: '/admin/system-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeRoute = ApiScrapeRouteImport.update({
  id: '/api/scrape',
  path: '/api/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendNotificationRoute = ApiSendNotificationRouteImport.update({
  id: '/api/send-notification',
  path: '/api/send-notification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const CartLoginRoute = CartLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CartRoute,
} as any)
const CartRegisterRoute = CartRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CartRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerSplatRoute = ResellerSplatRouteImport.update({
  id: '/reseller/$',
  path: '/reseller/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerAdBoostRoute = ResellerAdBoostRouteImport.update({
  id: '/reseller/ad-boost',
  path: '/reseller/ad-boost',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerDashboardRoute = ResellerDashboardRouteImport.update({
  id: '/reseller/dashboard',
  path: '/reseller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerLoginRoute = ResellerLoginRouteImport.update({
  id: '/reseller/login',
  path: '/reseller/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerMessagesRoute = ResellerMessagesRouteImport.update({
  id: '/reseller/messages',
  path: '/reseller/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerOrdersRoute = ResellerOrdersRouteImport.update({
  id: '/reseller/orders',
  path: '/reseller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerProfileRoute = ResellerProfileRouteImport.update({
  id: '/reseller/profile',
  path: '/reseller/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerRegisterRoute = ResellerRegisterRouteImport.update({
  id: '/reseller/register',
  path: '/reseller/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerShareTargetRoute = ResellerShareTargetRouteImport.update({
  id: '/reseller/share-target',
  path: '/reseller/share-target',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerShopRoute = ResellerShopRouteImport.update({
  id: '/reseller/shop',
  path: '/reseller/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchCustomersRoute = AdminAchCustomersRouteImport.update({
  id: '/admin/ach/customers',
  path: '/admin/ach/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAchFinancialRoute = AdminAchFinancialRouteImport.update({
  id: '/admin/ach/financial',
  path: '/admin/ach/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArsDepositRoute = AdminArsDepositRouteImport.update({
  id: '/admin/ars/deposit',
  path: '/admin/ars/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArsOrdersRoute = AdminArsOrdersRouteImport.update({
  id: '/admin/ars/orders',
  path: '/admin/ars/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArsPaymentInfoRoute = AdminArsPaymentInfoRouteImport.update({
  id: '/admin/ars/payment-info',
  path: '/admin/ars/payment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArsRetailShopsRoute = AdminArsRetailShopsRouteImport.update({
  id: '/admin/ars/retail-shops',
  path: '/admin/ars/retail-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArsWithdrawalRoute = AdminArsWithdrawalRouteImport.update({
  id: '/admin/ars/withdrawal',
  path: '/admin/ars/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthForgotPasswordRoute = AdminAuthForgotPasswordRouteImport.update({
  id: '/admin/auth/forgot-password',
  path: '/admin/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthSignInRoute = AdminAuthSignInRouteImport.update({
  id: '/admin/auth/sign-in',
  path: '/admin/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerCareOrderServicesRoute =
  AdminCustomerCareOrderServicesRouteImport.update({
    id: '/admin/customer-care/order-services',
    path: '/admin/customer-care/order-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomerCareResellerProfileRoute =
  AdminCustomerCareResellerProfileRouteImport.update({
    id: '/admin/customer-care/reseller-profile',
    path: '/admin/customer-care/reseller-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomerCareStaffsRoute = AdminCustomerCareStaffsRouteImport.update({
  id: '/admin/customer-care/staffs',
  path: '/admin/customer-care/staffs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerCareVirtualServicesRoute =
  AdminCustomerCareVirtualServicesRouteImport.update({
    id: '/admin/customer-care/virtual-services',
    path: '/admin/customer-care/virtual-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSlaAdministratorRoute = AdminSlaAdministratorRouteImport.update({
  id: '/admin/sla/administrator',
  path: '/admin/sla/administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaBroadcastNewsRoute = AdminSlaBroadcastNewsRouteImport.update({
  id: '/admin/sla/broadcast-news',
  path: '/admin/sla/broadcast-news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaOwnershipRoute = AdminSlaOwnershipRouteImport.update({
  id: '/admin/sla/ownership',
  path: '/admin/sla/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaReseller2AdminRoute = AdminSlaReseller2AdminRouteImport.update({
  id: '/admin/sla/reseller-2-admin',
  path: '/admin/sla/reseller-2-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaSiteAdvertisingRoute = AdminSlaSiteAdvertisingRouteImport.update({
  id: '/admin/sla/site-advertising',
  path: '/admin/sla/site-advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaSqcOrdersRoute = AdminSlaSqcOrdersRouteImport.update({
  id: '/admin/sla/sqc-orders',
  path: '/admin/sla/sqc-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlaStaffRoute = AdminSlaStaffRouteImport.update({
  id: '/admin/sla/staff',
  path: '/admin/sla/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApipublicRegisterResellerRoute =
  ApipublicRegisterResellerRouteImport.update({
    id: '/api/(public)/register-reseller',
    path: '/api/register-reseller',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCreateAdminRoute = ApiAdminCreateAdminRouteImport.update({
  id: '/api/admin/create-admin',
  path: '/api/admin/create-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateResellerRoute = ApiAdminCreateResellerRouteImport.update({
  id: '/api/admin/create-reseller',
  path: '/api/admin/create-reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteResellerRoute = ApiAdminDeleteResellerRouteImport.update({
  id: '/api/admin/delete-reseller',
  path: '/api/admin/delete-reseller',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteStaffRoute = ApiAdminDeleteStaffRouteImport.update({
  id: '/api/admin/delete-staff',
  path: '/api/admin/delete-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetResellerPasswordRoute =
  ApiAdminResetResellerPasswordRouteImport.update({
    id: '/api/admin/reset-reseller-password',
    path: '/api/admin/reset-reseller-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminVerifyAllRoute = ApiAdminVerifyAllRouteImport.update({
  id: '/api/admin/verify-all',
  path: '/api/admin/verify-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ResellerProfileCustomizeRoute =
  ResellerProfileCustomizeRouteImport.update({
    id: '/customize',
    path: '/customize',
    getParentRoute: () => ResellerProfileRoute,
  } as any)
const ApipublicResellerRequestResetRoute =
  ApipublicResellerRequestResetRouteImport.update({
    id: '/api/(public)/reseller/request-reset',
    path: '/api/reseller/request-reset',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/orders': typeof OrdersRoute
  '/returns-refunds': typeof ReturnsRefundsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/verification-compliance': typeof VerificationComplianceRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messenger': typeof AdminMessengerRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/system-logs': typeof AdminSystemLogsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/send-notification': typeof ApiSendNotificationRoute
  '/api/sync': typeof ApiSyncRoute
  '/cart/login': typeof CartLoginRoute
  '/cart/register': typeof CartRegisterRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/reseller/$': typeof ResellerSplatRoute
  '/reseller/ad-boost': typeof ResellerAdBoostRoute
  '/reseller/dashboard': typeof ResellerDashboardRoute
  '/reseller/login': typeof ResellerLoginRoute
  '/reseller/messages': typeof ResellerMessagesRoute
  '/reseller/orders': typeof ResellerOrdersRoute
  '/reseller/profile': typeof ResellerProfileRouteWithChildren
  '/reseller/register': typeof ResellerRegisterRoute
  '/reseller/share-target': typeof ResellerShareTargetRoute
  '/reseller/shop': typeof ResellerShopRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ach/customers': typeof AdminAchCustomersRoute
  '/admin/ach/financial': typeof AdminAchFinancialRoute
  '/admin/ars/deposit': typeof AdminArsDepositRoute
  '/admin/ars/orders': typeof AdminArsOrdersRoute
  '/admin/ars/payment-info': typeof AdminArsPaymentInfoRoute
  '/admin/ars/retail-shops': typeof AdminArsRetailShopsRoute
  '/admin/ars/withdrawal': typeof AdminArsWithdrawalRoute
  '/admin/auth/forgot-password': typeof AdminAuthForgotPasswordRoute
  '/admin/auth/sign-in': typeof AdminAuthSignInRoute
  '/admin/customer-care/order-services': typeof AdminCustomerCareOrderServicesRoute
  '/admin/customer-care/reseller-profile': typeof AdminCustomerCareResellerProfileRoute
  '/admin/customer-care/staffs': typeof AdminCustomerCareStaffsRoute
  '/admin/customer-care/virtual-services': typeof AdminCustomerCareVirtualServicesRoute
  '/admin/sla/administrator': typeof AdminSlaAdministratorRoute
  '/admin/sla/broadcast-news': typeof AdminSlaBroadcastNewsRoute
  '/admin/sla/ownership': typeof AdminSlaOwnershipRoute
  '/admin/sla/reseller-2-admin': typeof AdminSlaReseller2AdminRoute
  '/admin/sla/site-advertising': typeof AdminSlaSiteAdvertisingRoute
  '/admin/sla/sqc-orders': typeof AdminSlaSqcOrdersRoute
  '/admin/sla/staff': typeof AdminSlaStaffRoute
  '/api/register-reseller': typeof ApipublicRegisterResellerRoute
  '/api/admin/create-admin': typeof ApiAdminCreateAdminRoute
  '/api/admin/create-reseller': typeof ApiAdminCreateResellerRoute
  '/api/admin/delete-reseller': typeof ApiAdminDeleteResellerRoute
  '/api/admin/delete-staff': typeof ApiAdminDeleteStaffRoute
  '/api/admin/reset-reseller-password': typeof ApiAdminResetResellerPasswordRoute
  '/api/admin/verify-all': typeof ApiAdminVerifyAllRoute
  '/reseller/profile/customize': typeof ResellerProfileCustomizeRoute
  '/api/reseller/request-reset': typeof ApipublicResellerRequestResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/orders': typeof OrdersRoute
  '/returns-refunds': typeof ReturnsRefundsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/verification-compliance': typeof VerificationComplianceRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messenger': typeof AdminMessengerRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/system-logs': typeof AdminSystemLogsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/send-notification': typeof ApiSendNotificationRoute
  '/api/sync': typeof ApiSyncRoute
  '/cart/login': typeof CartLoginRoute
  '/cart/register': typeof CartRegisterRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/reseller/$': typeof ResellerSplatRoute
  '/reseller/ad-boost': typeof ResellerAdBoostRoute
  '/reseller/dashboard': typeof ResellerDashboardRoute
  '/reseller/login': typeof ResellerLoginRoute
  '/reseller/messages': typeof ResellerMessagesRoute
  '/reseller/orders': typeof ResellerOrdersRoute
  '/reseller/profile': typeof ResellerProfileRouteWithChildren
  '/reseller/register': typeof ResellerRegisterRoute
  '/reseller/share-target': typeof ResellerShareTargetRoute
  '/reseller/shop': typeof ResellerShopRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/ach/customers': typeof AdminAchCustomersRoute
  '/admin/ach/financial': typeof AdminAchFinancialRoute
  '/admin/ars/deposit': typeof AdminArsDepositRoute
  '/admin/ars/orders': typeof AdminArsOrdersRoute
  '/admin/ars/payment-info': typeof AdminArsPaymentInfoRoute
  '/admin/ars/retail-shops': typeof AdminArsRetailShopsRoute
  '/admin/ars/withdrawal': typeof AdminArsWithdrawalRoute
  '/admin/auth/forgot-password': typeof AdminAuthForgotPasswordRoute
  '/admin/auth/sign-in': typeof AdminAuthSignInRoute
  '/admin/customer-care/order-services': typeof AdminCustomerCareOrderServicesRoute
  '/admin/customer-care/reseller-profile': typeof AdminCustomerCareResellerProfileRoute
  '/admin/customer-care/staffs': typeof AdminCustomerCareStaffsRoute
  '/admin/customer-care/virtual-services': typeof AdminCustomerCareVirtualServicesRoute
  '/admin/sla/administrator': typeof AdminSlaAdministratorRoute
  '/admin/sla/broadcast-news': typeof AdminSlaBroadcastNewsRoute
  '/admin/sla/ownership': typeof AdminSlaOwnershipRoute
  '/admin/sla/reseller-2-admin': typeof AdminSlaReseller2AdminRoute
  '/admin/sla/site-advertising': typeof AdminSlaSiteAdvertisingRoute
  '/admin/sla/sqc-orders': typeof AdminSlaSqcOrdersRoute
  '/admin/sla/staff': typeof AdminSlaStaffRoute
  '/api/register-reseller': typeof ApipublicRegisterResellerRoute
  '/api/admin/create-admin': typeof ApiAdminCreateAdminRoute
  '/api/admin/create-reseller': typeof ApiAdminCreateResellerRoute
  '/api/admin/delete-reseller': typeof ApiAdminDeleteResellerRoute
  '/api/admin/delete-staff': typeof ApiAdminDeleteStaffRoute
  '/api/admin/reset-reseller-password': typeof ApiAdminResetResellerPasswordRoute
  '/api/admin/verify-all': typeof ApiAdminVerifyAllRoute
  '/reseller/profile/customize': typeof ResellerProfileCustomizeRoute
  '/api/reseller/request-reset': typeof ApipublicResellerRequestResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/orders': typeof OrdersRoute
  '/returns-refunds': typeof ReturnsRefundsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/verification-compliance': typeof VerificationComplianceRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customer-service': typeof AdminCustomerServiceRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/messenger': typeof AdminMessengerRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/system-logs': typeof AdminSystemLogsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/scrape': typeof ApiScrapeRoute
  '/api/send-notification': typeof ApiSendNotificationRoute
  '/api/sync': typeof ApiSyncRoute
  '/cart/login': typeof CartLoginRoute
  '/cart/register': typeof CartRegisterRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/reseller/$': typeof ResellerSplatRoute
  '/reseller/ad-boost': typeof ResellerAdBoostRoute
  '/reseller/dashboard': typeof ResellerDashboardRoute
  '/reseller/login': typeof ResellerLoginRoute
  '/reseller/messages': typeof ResellerMessagesRoute
  '/reseller/orders': typeof ResellerOrdersRoute
  '/reseller/profile': typeof ResellerProfileRouteWithChildren
  '/reseller/register': typeof ResellerRegisterRoute
  '/reseller/share-target': typeof ResellerShareTargetRoute
  '/reseller/shop': typeof ResellerShopRoute
  '/store/$slug': typeof StoreSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/ach/customers': typeof AdminAchCustomersRoute
  '/admin/ach/financial': typeof AdminAchFinancialRoute
  '/admin/ars/deposit': typeof AdminArsDepositRoute
  '/admin/ars/orders': typeof AdminArsOrdersRoute
  '/admin/ars/payment-info': typeof AdminArsPaymentInfoRoute
  '/admin/ars/retail-shops': typeof AdminArsRetailShopsRoute
  '/admin/ars/withdrawal': typeof AdminArsWithdrawalRoute
  '/admin/auth/forgot-password': typeof AdminAuthForgotPasswordRoute
  '/admin/auth/sign-in': typeof AdminAuthSignInRoute
  '/admin/customer-care/order-services': typeof AdminCustomerCareOrderServicesRoute
  '/admin/customer-care/reseller-profile': typeof AdminCustomerCareResellerProfileRoute
  '/admin/customer-care/staffs': typeof AdminCustomerCareStaffsRoute
  '/admin/customer-care/virtual-services': typeof AdminCustomerCareVirtualServicesRoute
  '/admin/sla/administrator': typeof AdminSlaAdministratorRoute
  '/admin/sla/broadcast-news': typeof AdminSlaBroadcastNewsRoute
  '/admin/sla/ownership': typeof AdminSlaOwnershipRoute
  '/admin/sla/reseller-2-admin': typeof AdminSlaReseller2AdminRoute
  '/admin/sla/site-advertising': typeof AdminSlaSiteAdvertisingRoute
  '/admin/sla/sqc-orders': typeof AdminSlaSqcOrdersRoute
  '/admin/sla/staff': typeof AdminSlaStaffRoute
  '/api/(public)/register-reseller': typeof ApipublicRegisterResellerRoute
  '/api/admin/create-admin': typeof ApiAdminCreateAdminRoute
  '/api/admin/create-reseller': typeof ApiAdminCreateResellerRoute
  '/api/admin/delete-reseller': typeof ApiAdminDeleteResellerRoute
  '/api/admin/delete-staff': typeof ApiAdminDeleteStaffRoute
  '/api/admin/reset-reseller-password': typeof ApiAdminResetResellerPasswordRoute
  '/api/admin/verify-all': typeof ApiAdminVerifyAllRoute
  '/reseller/profile/customize': typeof ResellerProfileCustomizeRoute
  '/api/(public)/reseller/request-reset': typeof ApipublicResellerRequestResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/orders'
    | '/returns-refunds'
    | '/shipping-policy'
    | '/verification-compliance'
    | '/admin/$'
    | '/admin/admins'
    | '/admin/alerts'
    | '/admin/audit-logs'
    | '/admin/campaigns'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/customer-service'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/messenger'
    | '/admin/orders'
    | '/admin/resellers'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/system'
    | '/admin/system-logs'
    | '/api/health'
    | '/api/scrape'
    | '/api/send-notification'
    | '/api/sync'
    | '/cart/login'
    | '/cart/register'
    | '/categories/$slug'
    | '/products/$id'
    | '/reseller/$'
    | '/reseller/ad-boost'
    | '/reseller/dashboard'
    | '/reseller/login'
    | '/reseller/messages'
    | '/reseller/orders'
    | '/reseller/profile'
    | '/reseller/register'
    | '/reseller/share-target'
    | '/reseller/shop'
    | '/store/$slug'
    | '/admin/'
    | '/admin/ach/customers'
    | '/admin/ach/financial'
    | '/admin/ars/deposit'
    | '/admin/ars/orders'
    | '/admin/ars/payment-info'
    | '/admin/ars/retail-shops'
    | '/admin/ars/withdrawal'
    | '/admin/auth/forgot-password'
    | '/admin/auth/sign-in'
    | '/admin/customer-care/order-services'
    | '/admin/customer-care/reseller-profile'
    | '/admin/customer-care/staffs'
    | '/admin/customer-care/virtual-services'
    | '/admin/sla/administrator'
    | '/admin/sla/broadcast-news'
    | '/admin/sla/ownership'
    | '/admin/sla/reseller-2-admin'
    | '/admin/sla/site-advertising'
    | '/admin/sla/sqc-orders'
    | '/admin/sla/staff'
    | '/api/register-reseller'
    | '/api/admin/create-admin'
    | '/api/admin/create-reseller'
    | '/api/admin/delete-reseller'
    | '/api/admin/delete-staff'
    | '/api/admin/reset-reseller-password'
    | '/api/admin/verify-all'
    | '/reseller/profile/customize'
    | '/api/reseller/request-reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/orders'
    | '/returns-refunds'
    | '/shipping-policy'
    | '/verification-compliance'
    | '/admin/$'
    | '/admin/admins'
    | '/admin/alerts'
    | '/admin/audit-logs'
    | '/admin/campaigns'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/customer-service'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/messenger'
    | '/admin/orders'
    | '/admin/resellers'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/system'
    | '/admin/system-logs'
    | '/api/health'
    | '/api/scrape'
    | '/api/send-notification'
    | '/api/sync'
    | '/cart/login'
    | '/cart/register'
    | '/categories/$slug'
    | '/products/$id'
    | '/reseller/$'
    | '/reseller/ad-boost'
    | '/reseller/dashboard'
    | '/reseller/login'
    | '/reseller/messages'
    | '/reseller/orders'
    | '/reseller/profile'
    | '/reseller/register'
    | '/reseller/share-target'
    | '/reseller/shop'
    | '/store/$slug'
    | '/admin'
    | '/admin/ach/customers'
    | '/admin/ach/financial'
    | '/admin/ars/deposit'
    | '/admin/ars/orders'
    | '/admin/ars/payment-info'
    | '/admin/ars/retail-shops'
    | '/admin/ars/withdrawal'
    | '/admin/auth/forgot-password'
    | '/admin/auth/sign-in'
    | '/admin/customer-care/order-services'
    | '/admin/customer-care/reseller-profile'
    | '/admin/customer-care/staffs'
    | '/admin/customer-care/virtual-services'
    | '/admin/sla/administrator'
    | '/admin/sla/broadcast-news'
    | '/admin/sla/ownership'
    | '/admin/sla/reseller-2-admin'
    | '/admin/sla/site-advertising'
    | '/admin/sla/sqc-orders'
    | '/admin/sla/staff'
    | '/api/register-reseller'
    | '/api/admin/create-admin'
    | '/api/admin/create-reseller'
    | '/api/admin/delete-reseller'
    | '/api/admin/delete-staff'
    | '/api/admin/reset-reseller-password'
    | '/api/admin/verify-all'
    | '/reseller/profile/customize'
    | '/api/reseller/request-reset'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/orders'
    | '/returns-refunds'
    | '/shipping-policy'
    | '/verification-compliance'
    | '/admin/$'
    | '/admin/admins'
    | '/admin/alerts'
    | '/admin/audit-logs'
    | '/admin/campaigns'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/customer-service'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/messenger'
    | '/admin/orders'
    | '/admin/resellers'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/system'
    | '/admin/system-logs'
    | '/api/health'
    | '/api/scrape'
    | '/api/send-notification'
    | '/api/sync'
    | '/cart/login'
    | '/cart/register'
    | '/categories/$slug'
    | '/products/$id'
    | '/reseller/$'
    | '/reseller/ad-boost'
    | '/reseller/dashboard'
    | '/reseller/login'
    | '/reseller/messages'
    | '/reseller/orders'
    | '/reseller/profile'
    | '/reseller/register'
    | '/reseller/share-target'
    | '/reseller/shop'
    | '/store/$slug'
    | '/admin/'
    | '/admin/ach/customers'
    | '/admin/ach/financial'
    | '/admin/ars/deposit'
    | '/admin/ars/orders'
    | '/admin/ars/payment-info'
    | '/admin/ars/retail-shops'
    | '/admin/ars/withdrawal'
    | '/admin/auth/forgot-password'
    | '/admin/auth/sign-in'
    | '/admin/customer-care/order-services'
    | '/admin/customer-care/reseller-profile'
    | '/admin/customer-care/staffs'
    | '/admin/customer-care/virtual-services'
    | '/admin/sla/administrator'
    | '/admin/sla/broadcast-news'
    | '/admin/sla/ownership'
    | '/admin/sla/reseller-2-admin'
    | '/admin/sla/site-advertising'
    | '/admin/sla/sqc-orders'
    | '/admin/sla/staff'
    | '/api/(public)/register-reseller'
    | '/api/admin/create-admin'
    | '/api/admin/create-reseller'
    | '/api/admin/delete-reseller'
    | '/api/admin/delete-staff'
    | '/api/admin/reset-reseller-password'
    | '/api/admin/verify-all'
    | '/reseller/profile/customize'
    | '/api/(public)/reseller/request-reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  ReturnsRefundsRoute: typeof ReturnsRefundsRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  VerificationComplianceRoute: typeof VerificationComplianceRoute
  AdminSplatRoute: typeof AdminSplatRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomerServiceRoute: typeof AdminCustomerServiceRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMessengerRoute: typeof AdminMessengerRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminResellersRoute: typeof AdminResellersRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminSystemLogsRoute: typeof AdminSystemLogsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiScrapeRoute: typeof ApiScrapeRoute
  ApiSendNotificationRoute: typeof ApiSendNotificationRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ResellerSplatRoute: typeof ResellerSplatRoute
  ResellerAdBoostRoute: typeof ResellerAdBoostRoute
  ResellerDashboardRoute: typeof ResellerDashboardRoute
  ResellerLoginRoute: typeof ResellerLoginRoute
  ResellerMessagesRoute: typeof ResellerMessagesRoute
  ResellerOrdersRoute: typeof ResellerOrdersRoute
  ResellerProfileRoute: typeof ResellerProfileRouteWithChildren
  ResellerRegisterRoute: typeof ResellerRegisterRoute
  ResellerShareTargetRoute: typeof ResellerShareTargetRoute
  ResellerShopRoute: typeof ResellerShopRoute
  StoreSlugRoute: typeof StoreSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAchCustomersRoute: typeof AdminAchCustomersRoute
  AdminAchFinancialRoute: typeof AdminAchFinancialRoute
  AdminArsDepositRoute: typeof AdminArsDepositRoute
  AdminArsOrdersRoute: typeof AdminArsOrdersRoute
  AdminArsPaymentInfoRoute: typeof AdminArsPaymentInfoRoute
  AdminArsRetailShopsRoute: typeof AdminArsRetailShopsRoute
  AdminArsWithdrawalRoute: typeof AdminArsWithdrawalRoute
  AdminAuthForgotPasswordRoute: typeof AdminAuthForgotPasswordRoute
  AdminAuthSignInRoute: typeof AdminAuthSignInRoute
  AdminCustomerCareOrderServicesRoute: typeof AdminCustomerCareOrderServicesRoute
  AdminCustomerCareResellerProfileRoute: typeof AdminCustomerCareResellerProfileRoute
  AdminCustomerCareStaffsRoute: typeof AdminCustomerCareStaffsRoute
  AdminCustomerCareVirtualServicesRoute: typeof AdminCustomerCareVirtualServicesRoute
  AdminSlaAdministratorRoute: typeof AdminSlaAdministratorRoute
  AdminSlaBroadcastNewsRoute: typeof AdminSlaBroadcastNewsRoute
  AdminSlaOwnershipRoute: typeof AdminSlaOwnershipRoute
  AdminSlaReseller2AdminRoute: typeof AdminSlaReseller2AdminRoute
  AdminSlaSiteAdvertisingRoute: typeof AdminSlaSiteAdvertisingRoute
  AdminSlaSqcOrdersRoute: typeof AdminSlaSqcOrdersRoute
  AdminSlaStaffRoute: typeof AdminSlaStaffRoute
  ApipublicRegisterResellerRoute: typeof ApipublicRegisterResellerRoute
  ApiAdminCreateAdminRoute: typeof ApiAdminCreateAdminRoute
  ApiAdminCreateResellerRoute: typeof ApiAdminCreateResellerRoute
  ApiAdminDeleteResellerRoute: typeof ApiAdminDeleteResellerRoute
  ApiAdminDeleteStaffRoute: typeof ApiAdminDeleteStaffRoute
  ApiAdminResetResellerPasswordRoute: typeof ApiAdminResetResellerPasswordRoute
  ApiAdminVerifyAllRoute: typeof ApiAdminVerifyAllRoute
  ApipublicResellerRequestResetRoute: typeof ApipublicResellerRequestResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-refunds': {
      id: '/returns-refunds'
      path: '/returns-refunds'
      fullPath: '/returns-refunds'
      preLoaderRoute: typeof ReturnsRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-compliance': {
      id: '/verification-compliance'
      path: '/verification-compliance'
      fullPath: '/verification-compliance'
      preLoaderRoute: typeof VerificationComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-service': {
      id: '/admin/customer-service'
      path: '/admin/customer-service'
      fullPath: '/admin/customer-service'
      preLoaderRoute: typeof AdminCustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messenger': {
      id: '/admin/messenger'
      path: '/admin/messenger'
      fullPath: '/admin/messenger'
      preLoaderRoute: typeof AdminMessengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/admin/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system-logs': {
      id: '/admin/system-logs'
      path: '/admin/system-logs'
      fullPath: '/admin/system-logs'
      preLoaderRoute: typeof AdminSystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape': {
      id: '/api/scrape'
      path: '/api/scrape'
      fullPath: '/api/scrape'
      preLoaderRoute: typeof ApiScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-notification': {
      id: '/api/send-notification'
      path: '/api/send-notification'
      fullPath: '/api/send-notification'
      preLoaderRoute: typeof ApiSendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/login': {
      id: '/cart/login'
      path: '/login'
      fullPath: '/cart/login'
      preLoaderRoute: typeof CartLoginRouteImport
      parentRoute: typeof CartRoute
    }
    '/cart/register': {
      id: '/cart/register'
      path: '/register'
      fullPath: '/cart/register'
      preLoaderRoute: typeof CartRegisterRouteImport
      parentRoute: typeof CartRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/$': {
      id: '/reseller/$'
      path: '/reseller/$'
      fullPath: '/reseller/$'
      preLoaderRoute: typeof ResellerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/ad-boost': {
      id: '/reseller/ad-boost'
      path: '/reseller/ad-boost'
      fullPath: '/reseller/ad-boost'
      preLoaderRoute: typeof ResellerAdBoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/dashboard': {
      id: '/reseller/dashboard'
      path: '/reseller/dashboard'
      fullPath: '/reseller/dashboard'
      preLoaderRoute: typeof ResellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/login': {
      id: '/reseller/login'
      path: '/reseller/login'
      fullPath: '/reseller/login'
      preLoaderRoute: typeof ResellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/messages': {
      id: '/reseller/messages'
      path: '/reseller/messages'
      fullPath: '/reseller/messages'
      preLoaderRoute: typeof ResellerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/orders': {
      id: '/reseller/orders'
      path: '/reseller/orders'
      fullPath: '/reseller/orders'
      preLoaderRoute: typeof ResellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/profile': {
      id: '/reseller/profile'
      path: '/reseller/profile'
      fullPath: '/reseller/profile'
      preLoaderRoute: typeof ResellerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/register': {
      id: '/reseller/register'
      path: '/reseller/register'
      fullPath: '/reseller/register'
      preLoaderRoute: typeof ResellerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/share-target': {
      id: '/reseller/share-target'
      path: '/reseller/share-target'
      fullPath: '/reseller/share-target'
      preLoaderRoute: typeof ResellerShareTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/shop': {
      id: '/reseller/shop'
      path: '/reseller/shop'
      fullPath: '/reseller/shop'
      preLoaderRoute: typeof ResellerShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ach/customers': {
      id: '/admin/ach/customers'
      path: '/admin/ach/customers'
      fullPath: '/admin/ach/customers'
      preLoaderRoute: typeof AdminAchCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ach/financial': {
      id: '/admin/ach/financial'
      path: '/admin/ach/financial'
      fullPath: '/admin/ach/financial'
      preLoaderRoute: typeof AdminAchFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ars/deposit': {
      id: '/admin/ars/deposit'
      path: '/admin/ars/deposit'
      fullPath: '/admin/ars/deposit'
      preLoaderRoute: typeof AdminArsDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ars/orders': {
      id: '/admin/ars/orders'
      path: '/admin/ars/orders'
      fullPath: '/admin/ars/orders'
      preLoaderRoute: typeof AdminArsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ars/payment-info': {
      id: '/admin/ars/payment-info'
      path: '/admin/ars/payment-info'
      fullPath: '/admin/ars/payment-info'
      preLoaderRoute: typeof AdminArsPaymentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ars/retail-shops': {
      id: '/admin/ars/retail-shops'
      path: '/admin/ars/retail-shops'
      fullPath: '/admin/ars/retail-shops'
      preLoaderRoute: typeof AdminArsRetailShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ars/withdrawal': {
      id: '/admin/ars/withdrawal'
      path: '/admin/ars/withdrawal'
      fullPath: '/admin/ars/withdrawal'
      preLoaderRoute: typeof AdminArsWithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth/forgot-password': {
      id: '/admin/auth/forgot-password'
      path: '/admin/auth/forgot-password'
      fullPath: '/admin/auth/forgot-password'
      preLoaderRoute: typeof AdminAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth/sign-in': {
      id: '/admin/auth/sign-in'
      path: '/admin/auth/sign-in'
      fullPath: '/admin/auth/sign-in'
      preLoaderRoute: typeof AdminAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-care/order-services': {
      id: '/admin/customer-care/order-services'
      path: '/admin/customer-care/order-services'
      fullPath: '/admin/customer-care/order-services'
      preLoaderRoute: typeof AdminCustomerCareOrderServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-care/reseller-profile': {
      id: '/admin/customer-care/reseller-profile'
      path: '/admin/customer-care/reseller-profile'
      fullPath: '/admin/customer-care/reseller-profile'
      preLoaderRoute: typeof AdminCustomerCareResellerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-care/staffs': {
      id: '/admin/customer-care/staffs'
      path: '/admin/customer-care/staffs'
      fullPath: '/admin/customer-care/staffs'
      preLoaderRoute: typeof AdminCustomerCareStaffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-care/virtual-services': {
      id: '/admin/customer-care/virtual-services'
      path: '/admin/customer-care/virtual-services'
      fullPath: '/admin/customer-care/virtual-services'
      preLoaderRoute: typeof AdminCustomerCareVirtualServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/administrator': {
      id: '/admin/sla/administrator'
      path: '/admin/sla/administrator'
      fullPath: '/admin/sla/administrator'
      preLoaderRoute: typeof AdminSlaAdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/broadcast-news': {
      id: '/admin/sla/broadcast-news'
      path: '/admin/sla/broadcast-news'
      fullPath: '/admin/sla/broadcast-news'
      preLoaderRoute: typeof AdminSlaBroadcastNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/ownership': {
      id: '/admin/sla/ownership'
      path: '/admin/sla/ownership'
      fullPath: '/admin/sla/ownership'
      preLoaderRoute: typeof AdminSlaOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/reseller-2-admin': {
      id: '/admin/sla/reseller-2-admin'
      path: '/admin/sla/reseller-2-admin'
      fullPath: '/admin/sla/reseller-2-admin'
      preLoaderRoute: typeof AdminSlaReseller2AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/site-advertising': {
      id: '/admin/sla/site-advertising'
      path: '/admin/sla/site-advertising'
      fullPath: '/admin/sla/site-advertising'
      preLoaderRoute: typeof AdminSlaSiteAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/sqc-orders': {
      id: '/admin/sla/sqc-orders'
      path: '/admin/sla/sqc-orders'
      fullPath: '/admin/sla/sqc-orders'
      preLoaderRoute: typeof AdminSlaSqcOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sla/staff': {
      id: '/admin/sla/staff'
      path: '/admin/sla/staff'
      fullPath: '/admin/sla/staff'
      preLoaderRoute: typeof AdminSlaStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/(public)/register-reseller': {
      id: '/api/(public)/register-reseller'
      path: '/api/register-reseller'
      fullPath: '/api/register-reseller'
      preLoaderRoute: typeof ApipublicRegisterResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-admin': {
      id: '/api/admin/create-admin'
      path: '/api/admin/create-admin'
      fullPath: '/api/admin/create-admin'
      preLoaderRoute: typeof ApiAdminCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-reseller': {
      id: '/api/admin/create-reseller'
      path: '/api/admin/create-reseller'
      fullPath: '/api/admin/create-reseller'
      preLoaderRoute: typeof ApiAdminCreateResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-reseller': {
      id: '/api/admin/delete-reseller'
      path: '/api/admin/delete-reseller'
      fullPath: '/api/admin/delete-reseller'
      preLoaderRoute: typeof ApiAdminDeleteResellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-staff': {
      id: '/api/admin/delete-staff'
      path: '/api/admin/delete-staff'
      fullPath: '/api/admin/delete-staff'
      preLoaderRoute: typeof ApiAdminDeleteStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset-reseller-password': {
      id: '/api/admin/reset-reseller-password'
      path: '/api/admin/reset-reseller-password'
      fullPath: '/api/admin/reset-reseller-password'
      preLoaderRoute: typeof ApiAdminResetResellerPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify-all': {
      id: '/api/admin/verify-all'
      path: '/api/admin/verify-all'
      fullPath: '/api/admin/verify-all'
      preLoaderRoute: typeof ApiAdminVerifyAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reseller/profile/customize': {
      id: '/reseller/profile/customize'
      path: '/customize'
      fullPath: '/reseller/profile/customize'
      preLoaderRoute: typeof ResellerProfileCustomizeRouteImport
      parentRoute: typeof ResellerProfileRoute
    }
    '/api/(public)/reseller/request-reset': {
      id: '/api/(public)/reseller/request-reset'
      path: '/api/reseller/request-reset'
      fullPath: '/api/reseller/request-reset'
      preLoaderRoute: typeof ApipublicResellerRequestResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CartRouteChildren {
  CartLoginRoute: typeof CartLoginRoute
  CartRegisterRoute: typeof CartRegisterRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartLoginRoute: CartLoginRoute,
  CartRegisterRoute: CartRegisterRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ResellerProfileRouteChildren {
  ResellerProfileCustomizeRoute: typeof ResellerProfileCustomizeRoute
}

const ResellerProfileRouteChildren: ResellerProfileRouteChildren = {
  ResellerProfileCustomizeRoute: ResellerProfileCustomizeRoute,
}

const ResellerProfileRouteWithChildren = ResellerProfileRoute._addFileChildren(
  ResellerProfileRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  OrdersRoute: OrdersRoute,
  ReturnsRefundsRoute: ReturnsRefundsRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  VerificationComplianceRoute: VerificationComplianceRoute,
  AdminSplatRoute: AdminSplatRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCustomerServiceRoute: AdminCustomerServiceRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMessengerRoute: AdminMessengerRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminResellersRoute: AdminResellersRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminSystemLogsRoute: AdminSystemLogsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiScrapeRoute: ApiScrapeRoute,
  ApiSendNotificationRoute: ApiSendNotificationRoute,
  ApiSyncRoute: ApiSyncRoute,
  ProductsIdRoute: ProductsIdRoute,
  ResellerSplatRoute: ResellerSplatRoute,
  ResellerAdBoostRoute: ResellerAdBoostRoute,
  ResellerDashboardRoute: ResellerDashboardRoute,
  ResellerLoginRoute: ResellerLoginRoute,
  ResellerMessagesRoute: ResellerMessagesRoute,
  ResellerOrdersRoute: ResellerOrdersRoute,
  ResellerProfileRoute: ResellerProfileRouteWithChildren,
  ResellerRegisterRoute: ResellerRegisterRoute,
  ResellerShareTargetRoute: ResellerShareTargetRoute,
  ResellerShopRoute: ResellerShopRoute,
  StoreSlugRoute: StoreSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAchCustomersRoute: AdminAchCustomersRoute,
  AdminAchFinancialRoute: AdminAchFinancialRoute,
  AdminArsDepositRoute: AdminArsDepositRoute,
  AdminArsOrdersRoute: AdminArsOrdersRoute,
  AdminArsPaymentInfoRoute: AdminArsPaymentInfoRoute,
  AdminArsRetailShopsRoute: AdminArsRetailShopsRoute,
  AdminArsWithdrawalRoute: AdminArsWithdrawalRoute,
  AdminAuthForgotPasswordRoute: AdminAuthForgotPasswordRoute,
  AdminAuthSignInRoute: AdminAuthSignInRoute,
  AdminCustomerCareOrderServicesRoute: AdminCustomerCareOrderServicesRoute,
  AdminCustomerCareResellerProfileRoute: AdminCustomerCareResellerProfileRoute,
  AdminCustomerCareStaffsRoute: AdminCustomerCareStaffsRoute,
  AdminCustomerCareVirtualServicesRoute: AdminCustomerCareVirtualServicesRoute,
  AdminSlaAdministratorRoute: AdminSlaAdministratorRoute,
  AdminSlaBroadcastNewsRoute: AdminSlaBroadcastNewsRoute,
  AdminSlaOwnershipRoute: AdminSlaOwnershipRoute,
  AdminSlaReseller2AdminRoute: AdminSlaReseller2AdminRoute,
  AdminSlaSiteAdvertisingRoute: AdminSlaSiteAdvertisingRoute,
  AdminSlaSqcOrdersRoute: AdminSlaSqcOrdersRoute,
  AdminSlaStaffRoute: AdminSlaStaffRoute,
  ApipublicRegisterResellerRoute: ApipublicRegisterResellerRoute,
  ApiAdminCreateAdminRoute: ApiAdminCreateAdminRoute,
  ApiAdminCreateResellerRoute: ApiAdminCreateResellerRoute,
  ApiAdminDeleteResellerRoute: ApiAdminDeleteResellerRoute,
  ApiAdminDeleteStaffRoute: ApiAdminDeleteStaffRoute,
  ApiAdminResetResellerPasswordRoute: ApiAdminResetResellerPasswordRoute,
  ApiAdminVerifyAllRoute: ApiAdminVerifyAllRoute,
  ApipublicResellerRequestResetRoute: ApipublicResellerRequestResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
